=== Death-Truction/Conversation-Engine/Conversation-Engine/conversation-engine-core/src/main/resources/SkillStateMachine_Schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "SkillStateMachine",
	"description": "A Skill State Machine",
	"$defs": {
		"state": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				}
			},
			"required": ["name"]
		},
		"transition": {
			"type": "object",
			"properties": {
				"source": {
					"type": "string"
				},
				"target": {
					"type": "string"
				},
				"trigger": {
					"type": "string"
				}
			},
			"required": ["source", "target", "trigger"]
		}
	},
	
	"type": "object",
	
	"properties": {
		"states": {
			"type": "array",
			"items": {
				"$ref": "#/$defs/state"
			},
			"minItems": 2,
			"uniqueItems": true
		},
		"transitions": {
			"type": "array",
			"items": {
				"$ref": "#/$defs/transition"
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"startAt": {
			"description": "The name of the starting state",
			"type": "string"
		},
		"endAt": {
			"description": "The name of the ending state",
			"type": "string"
		},
		"name": {
			"description": "The name skill",
			"type": "string"
		},
		"usedEntities": {
			"description": "the entities, that the skill uses",
			"type": "array",
			"items": {
				"type": "string"
			},
			"uniqueItems": true			
		},
		"usedIntents": {
			"description": "the intents the skill can execute",
			"type": "array",
			"items": {
				"type": "string"
			},
			"uniqueItems": true
		}
			
	},
	"required": ["states", "transitions", "startAt", "endAt", "name", "usedEntities", "usedIntents"]
}

=== Death-Truction/Conversation-Engine/ConversationsEngine/conversations-engine-statemachine/src/test/resources/json_schema_test/WrongTransitionTrigger.json
{
	"states": [
		{
			"name": "Start"
		},
		{
			"name": "Mid"
		},
		{
			"name": "End"
		}
	],	
	"transitions": [
		{
			"source": "Start",
			"target": "Mid",
			"trigger": "MISSING_ENTITIES"
		},
		{
			"source": "Start",
			"target": "End",
			"trigger": "SUCCESS"
		},
		{
			"source": "Mid",
			"target": "End",
			"trigger": "SUCCESSs"
		},
		{
			"source": "Mid",
			"target": "End",
			"trigger": "STAY"
		},
		{
			"source": "Mid",
			"target": "End",
			"trigger": "FAILED"
		}
	],
	"startAt": "Start",
	"endAt": "End",
	"name": "RecipeSkill",
	"usedEntities": [
		"recipeSearchIngredients", 
		"ingredients"
	],
	"usedIntents": [
		"recipeSearch",
		"recipeSelect"
	]
}

=== Death-Truction/Conversation-Engine/Conversation-Engine/src/test/resources/generate_skill_state_machine/WrongStateNameTransitionSource.json
{
	"states": [
		{
			"name": "Start"
		},
		{
			"name": "Mid"
		},
		{
			"name": "End"
		}
	],	
	"transitions": [
		{
			"source": "s",
			"target": "Mid",
			"trigger": "MISSING_ENTITIES"
		},
		{
			"source": "Start",
			"target": "End",
			"trigger": "SUCCESS"
		},
		{
			"source": "Mid",
			"target": "End",
			"trigger": "SUCCESS"
		}
	],
	"startAt": "Start",
	"endAt": "End",
	"name": "RecipeSkill",
	"usedEntities": [
		"recipeSearchIngredients", 
		"ingredients"
	],
	"usedIntents": [
		"recipeSearch",
		"recipeSelect"
	]
}

=== Death-Truction/Conversation-Engine/ConversationsEngine/conversations-engine-statemachine/src/test/resources/json_schema_test/NonUniqueEntries.json
{
	"states": [
		{
			"name": "Start"
		},
		{
			"name": "Mid"
		},
		{
			"name": "Mid"
		}
	],	
	"transitions": [
		{
			"source": "Start",
			"target": "Mid",
			"trigger": "MISSING_ENTITIES"
		},
		{
			"source": "Start",
			"target": "End",
			"trigger": "SUCCESS"
		},
		{
			"source": "Mid",
			"target": "End",
			"trigger": "SUCCESS"
		},
		{
			"source": "Mid",
			"target": "End",
			"trigger": "SUCCESS"
		}
	],
	"startAt": "Start",
	"endAt": "End",
	"name": "RecipeSkill",
	"usedEntities": [
		"recipeSearchIngredients", 
		"ingredients",
		"ingredients"
	],
	"usedIntents": [
		"recipeSearch",
		"recipeSelect",
		"recipeSelect"
	]
}
